/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://tucb2bsir5bh3mdr3ug4z5exqu.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-cvoep5bipjfgjnq2gdni4bzgvy",
    "aws_cognito_identity_pool_id": "eu-west-2:210f2475-877a-4e9f-a33d-54caee0c47a6",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_TewbYW8wo",
    "aws_user_pools_web_client_id": "3hcjjtg3qdipok5lrh9a7tmr92",
    "oauth": {},
    "aws_user_files_s3_bucket": "redditclone206134973dd14339a9ad44620e05ddd6182116-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
